### ISSUE TITLE
Sunset legacy `ipfs-ds-convert` tool

### ISSUE THREAD

**Issue by lidel** [ipfs-inactive/ipfs-ds-convert#50]
This project has not being maintained, was created in go-ipfs times, only supports ancient badgerv1 which we want to sunset, and makes little sense to exist now that we have more implementations than Kubo.

As discussed in https://github.com/ipfs/kubo/issues/10347#issuecomment-2388689056 we'd rather have converter built-into Kubo, than have this confusingly named tool.

## TODO

- [x] update readme informing that project is no longer relevant
- [x] hide it from `dist.ipfs.tech` by adding it to ignored lists [here](https://github.com/ipfs/distributions/blob/76525ae9614d54ffc3337c5cbc3a31c73a45421e/site/config.toml#L10) and [here](https://github.com/ipfs/distributions/blob/master/ignored-during-nightly)
  - [x]  https://github.com/ipfs/distributions/pull/1101
- [x] remove from docs website https://docs.ipfs.tech/how-to/default-profile/#converting-profiles
  - [x] https://github.com/ipfs/ipfs-docs/pull/1935
- [x] close this and other issues
- [ ] move to https://github.com/ipfs-inactive/
- [x] archive this repository
